######################################################################
# Automatically generated by qmake (3.0) Wed Mar 18 16:21:19 2015
######################################################################

TEMPLATE = app
TARGET = LuxIRC
INCLUDEPATH += .
QT += widgets

# Input
HEADERS += ChangeNickDlg.h MainWindow.h NetworkDlg.h
FORMS += ChangeNickDlg.ui MainWindow.ui NetworkDlg.ui
SOURCES += ChangeNickDlg.cpp main.cpp MainWindow.cpp NetworkDlg.cpp
