######################################################################
# Automatically generated by qmake (3.0) Mon Apr 11 12:43:39 2016
######################################################################

TEMPLATE = app
TARGET = testing
INCLUDEPATH += .

# Input
SOURCES += main.cpp

QT += network
